version: '3.8'

services:
  # --- Serviço PostgreSQL ---
  my-postgres:
    image: postgres
    container_name: my-postgres
    restart: unless-stopped
    ports:
      - "5433:5432" # Host:Container
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/pgdata
    networks:
      - my-network

  # --- Serviço pgAdmin 4 ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_SETUP_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_SETUP_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "15432:80" # Host:Container
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - my-network
    depends_on:
      - my-postgres

# --- Configuração da Rede ---
networks:
  my-network:
    driver: bridge

# --- Declaração de Volumes Nomeados ---
volumes:
  pgadmin_data:
